/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ManageAdminRouteImport } from './routes/manage-admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EpisodeIdRouteImport } from './routes/episode.$id'
import { Route as ContentIdRouteImport } from './routes/content.$id'

const ManageAdminRoute = ManageAdminRouteImport.update({
  id: '/manage-admin',
  path: '/manage-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EpisodeIdRoute = EpisodeIdRouteImport.update({
  id: '/episode/$id',
  path: '/episode/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentIdRoute = ContentIdRouteImport.update({
  id: '/content/$id',
  path: '/content/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/manage-admin': typeof ManageAdminRoute
  '/content/$id': typeof ContentIdRoute
  '/episode/$id': typeof EpisodeIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/manage-admin': typeof ManageAdminRoute
  '/content/$id': typeof ContentIdRoute
  '/episode/$id': typeof EpisodeIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/manage-admin': typeof ManageAdminRoute
  '/content/$id': typeof ContentIdRoute
  '/episode/$id': typeof EpisodeIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/manage-admin' | '/content/$id' | '/episode/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/manage-admin' | '/content/$id' | '/episode/$id'
  id: '__root__' | '/' | '/manage-admin' | '/content/$id' | '/episode/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ManageAdminRoute: typeof ManageAdminRoute
  ContentIdRoute: typeof ContentIdRoute
  EpisodeIdRoute: typeof EpisodeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/manage-admin': {
      id: '/manage-admin'
      path: '/manage-admin'
      fullPath: '/manage-admin'
      preLoaderRoute: typeof ManageAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/episode/$id': {
      id: '/episode/$id'
      path: '/episode/$id'
      fullPath: '/episode/$id'
      preLoaderRoute: typeof EpisodeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content/$id': {
      id: '/content/$id'
      path: '/content/$id'
      fullPath: '/content/$id'
      preLoaderRoute: typeof ContentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ManageAdminRoute: ManageAdminRoute,
  ContentIdRoute: ContentIdRoute,
  EpisodeIdRoute: EpisodeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
